"""Generate only our custom contexts; never replace Issabel's Queue dialplan."""


def render(config):
    return '''; Generated by issabel-crm apply. Edit issabel_crm.conf, not this file.
; Target: Asterisk 16/18. Verify VQ_AGI support and setinterfacevar on installed queues.
[issabel-crm-entry]
exten => s,1,Answer()
 same => n,Set(CRM_DEST_TYPE=queue)
 same => n,Set(CRM_DEST=FALLBACK)
 same => n,Set(__CRM_AFFILIATE_ID=)
 same => n,Set(__CRM_CUIL=)
 same => n,Set(CRM_RESULT=agi_failed)
 same => n,AGI(issabel-crm-identify.agi)
 same => n,GotoIf($["${CRM_DEST_TYPE}"="external"]?external)
 same => n,Goto(queue)
 same => n(external),Dial(Local/${CRM_DEST}@from-internal/n,OUTBOUND_TIMEOUT,g)
 same => n,GotoIf($["${DIALSTATUS}"="ANSWER"]?done)
 same => n,Set(CRM_DEST=FALLBACK)
 same => n,Set(CRM_DEST_TYPE=queue)
 same => n,Set(CRM_RESULT=external_failed)
 same => n(queue),Set(__CRM_QUEUE=${CRM_DEST})
 same => n,Set(__CRM_PREVIOUS_QAGI=${IF($[${LEN(${VQ_AGI})}>0]?${VQ_AGI}:${QAGI})})
 same => n,Set(VQ_AGI=issabel-crm-answer.agi)
 same => n,Goto(ext-queues,${CRM_DEST},1)
 same => n(done),Hangup()
'''.replace('FALLBACK', config['fallback_queue']).replace('OUTBOUND_TIMEOUT', str(config['external_timeout']))
