"""Generate only our custom contexts; never replace Issabel's Queue dialplan."""


def render(config):
    return '''; Generated by issabel-crm apply. Edit issabel_crm.conf, not this file.
; Target: Asterisk 16/18. Verify VQ_AGI support and setinterfacevar on installed queues.
[issabel-crm-entry]
exten => s,1,Answer()
 same => n,Set(CALLFLOW_ROUTING_DESTINATION_TYPE=queue)
 same => n,Set(CALLFLOW_ROUTING_DESTINATION_NUMBER=FALLBACK)
 same => n,Set(__CALLFLOW_CRM_AFFILIATE_ID=)
 same => n,Set(__CALLFLOW_AFFILIATE_CUIL=)
 same => n,Set(CALLFLOW_ROUTING_STATUS=agi_failed)
 same => n,AGI(issabel-crm-identify.agi)
 same => n,GotoIf($["${CALLFLOW_ROUTING_DESTINATION_TYPE}"="external"]?external)
 same => n,Goto(queue)
 same => n(external),Dial(Local/${CALLFLOW_ROUTING_DESTINATION_NUMBER}@from-internal/n,OUTBOUND_TIMEOUT,g)
 same => n,GotoIf($["${DIALSTATUS}"="ANSWER"]?done)
 same => n,Set(CALLFLOW_ROUTING_DESTINATION_NUMBER=FALLBACK)
 same => n,Set(CALLFLOW_ROUTING_DESTINATION_TYPE=queue)
 same => n,Set(CALLFLOW_ROUTING_STATUS=external_failed)
 same => n(queue),Set(__CALLFLOW_QUEUE_NAME=${CALLFLOW_ROUTING_DESTINATION_NUMBER})
 same => n,Set(__CALLFLOW_QUEUE_PREVIOUS_ANSWER_AGI=${IF($[${LEN(${VQ_AGI})}>0]?${VQ_AGI}:${QAGI})})
 same => n,Set(VQ_AGI=issabel-crm-answer.agi)
 same => n,Goto(ext-queues,${CALLFLOW_ROUTING_DESTINATION_NUMBER},1)
 same => n(done),Hangup()
'''.replace('FALLBACK', config['fallback_queue']).replace('OUTBOUND_TIMEOUT', str(config['external_timeout']))
